from django.urls import path
from . import views, views_hod
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('register/student/', views.StudentRegistrationView.as_view(), name='student_register'),
    path('register/staff/', views.StaffRegistrationView.as_view(), name='staff_register'),
    path('institution/', views.institution, name='institution'),
    path('messages/', views.messages_view, name='messages'),
    path('attendance/', views.attendance, name='attendance'),
    path('mark-attendance/', views.mark_attendance, name='mark_attendance'),
    path('take-attendance/<int:subject_id>/', views.take_attendance, name='take_attendance'),
    path('take-attendance/<int:subject_id>/<str:date>/', views.take_attendance, name='take_attendance_date'),
    path('assignments/', views.assignments, name='assignments'),
    path('assignments/submit/<int:assignment_id>/', views.submit_assignment, name='submit_assignment'),
    path('assignments/view-submission/<int:submission_id>/', views.view_submission, name='view_submission'),
    path('exam-schedules/', views.exam_schedules, name='exam_schedules'),
    path('reports/', views.reports, name='reports'),
    path('assessments/', views.assessments, name='assessments'),
    path('holidays/', views.holidays, name='holidays'),
    path('timetable/', views.timetable, name='timetable'),
    path('teaching-content/', views.teaching_content, name='teaching_content'),
    path('leave/', views.leave, name='leave'),
    path('services/', views.services, name='services'),
    path('billing/', views.billing, name='billing'),
    path('enrollment/', views.enrollment, name='enrollment'),
    path('student/dashboard/', views.student_dashboard, name='student_dashboard'),
    path('staff/dashboard/', views.staff_dashboard, name='staff_dashboard'),
    path('profile/', views.profile, name='profile'),
    path('student/fee/', views.student_fee, name='student_fee'),
    path('student/results/', views.student_results, name='student_results'),
    path('semester-enrollment/', views.semester_enrollment, name='semester_enrollment'),
    path('activity/', views.activity, name='activity'),
    path('feedback/', views.feedback, name='feedback'),
    path('announcement/', views.announcement, name='announcement'),
    path('professional-profile/', views.professional_profile, name='professional_profile'),
    path('professional-profile/<str:username>/', views.professional_profile, name='professional_profile_user'),
    path('professional-profile/edit/', views.edit_professional_profile, name='edit_professional_profile'),
    path('professional-profile/add-experience/', views.add_experience, name='add_experience'),
    path('professional-profile/add-education/', views.add_education, name='add_education'),
    path('professional-profile/add-publication/', views.add_publication, name='add_publication'),
    path('staff/assignments/', views.staff_assignments, name='staff_assignments'),
    path('staff/assignments/create/', views.create_assignment, name='create_assignment'),
    path('staff/assignments/edit/<int:assignment_id>/', views.edit_assignment, name='edit_assignment'),
    path('staff/assignments/submissions/<int:assignment_id>/', views.assignment_submissions, name='assignment_submissions'),
    path('staff/assignments/grade/<int:submission_id>/', views.grade_submission, name='grade_submission'),
    path('hod/dashboard/', views_hod.hod_dashboard, name='hod_dashboard'),
    path('hod/subjects/', views_hod.manage_subjects, name='hod_manage_subjects'),
    path('hod/staff/', views_hod.manage_staff, name='hod_manage_staff'),
    path('hod/subjects/<int:subject_id>/', views_hod.view_subject_details, name='hod_view_subject_details'),
] 