# Generated by Django 5.1.7 on 2025-03-17 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_assignment_assignmentsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department_managed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_head', to='accounts.department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_department_head',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('staff', 'Staff'), ('hod', 'HOD')], default='student', max_length=10),
        ),
    ]
